language: c
 
before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null
  - mozroots --import --sync
  - export EnableNuGetPackageRestore=true

script:
  - xbuild Anterec.ControllerLess.sln
